# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code Blog - Marcus Wong
email: marcus@wongm.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on technology and software development from Marcus Wong
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://code.wongm.com" # the base hostname & protocol for your site
twitter_username: aussiewongm
github_username:  wongm
permalink: /:year/:title.html

# Build settings
markdown: kramdown
